language: node_js
node_js:
  - "9"

script:
  - npm run build

after_success:
    - npm install ci-publish
    - $(npm bin)/ci-publish || true
deploy:
  provider: releases
  api_key:
    secure: $RELEASE_API_TOKEN
  file:
    - "dist/zero-angularjs-helper.js"
    - "dist/zero-angularjs-helper.min.js"
  skip_cleanup: true
  on:
    repo: zerosuxx/zero-angularjs-helper
    tags: true

